# Generated by Django 6.0.5 on 2026-06-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_review_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="comment",
        ),
    ]
