# Generated by Django 6.0.5 on 2026-06-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_rename_date_review_created_at_review_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
