# Generated by Django 6.0.5 on 2026-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Paid", "Not Paid"),
                    ("Ready to Ship", "Ready to Ship"),
                    ("Pending", "Pending"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
