# Generated by Django 6.0.5 on 2026-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=562, max_digits=10),
            preserve_default=False,
        ),
    ]
